version: '3'
services:
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: frontend
    volumes:
       - ./frontend:/app
       - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
