# https://blog.benoitblanchon.fr/github-action-run-ssh-commands/
name: sshTest
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  job_one:
    name: Deploy
    runs-on: self-hosted
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: larry
          SSH_KEY: ${{ secrets.FAST_VUE3_DOCKER_WORKFLOW_PRIV_KEY }}
          SSH_HOST: craulio.com
