# https://blog.benoitblanchon.fr/github-action-run-ssh-commands/
name: sshTest
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  job_one:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: test ssh
        uses: appleboy/ssh-action@master
        with:
          host: craulio.com
          username: larry
          key: ${{ secrets.FAST_VUE3_DOCKER_WORKFLOW_PRIV_KEY }}
          port: 22
          script: |
            cd /home/larry/www
            git pull origin main
            git status
        run: |
          mkdir -p ~/.ssh/
          echo "FAST_VUE3_DOCKER_WORKFLOW_PRIV_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          cd /home/larry/www
          git pull origin main
          git status
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.FAST_VUE3_DOCKER_WORKFLOW_PRIV_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
