name: SSH Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          SSH_PRIVATE_KEY: ${{secrets.FAST_VUE3_DOCKER_WORKFLOW_PRIV_KEY}}
          REMOTE_HOST: craulio.com
          REMOTE_USER: larry
          REMOTE_PORT: 22
          SOURCE: "dist/"
          TARGET: /home/larry/www/dist
